spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:illustudy
    username: sa
    password: 

  h2:
    console:
      enabled: true
      
  servlet:
    multipart:
      max-file-size: 32MB
      max-request-size: 32MB
      
image:
  local: true